version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:dev
    # image: ghcr.io/godd6366/homepage:dev
    container_name: homepage
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3101:3000
    restart: always
    networks:
      - traefik
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.homepage.entrypoints: https
      traefik.http.routers.homepage.rule: Host(`tab.godd.site`)
      traefik.http.routers.homepage.tls: true
      traefik.http.routers.homepage.tls.certresolver: myresolver
      traefik.http.routers.homepage.tls.domains[0].main: godd.site
      traefik.http.routers.homepage.tls.domains[0].sans: "*.godd.site"
networks:
  traefik:
    external: true
