---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

- logo:
    # icon: https://i.imgur.com/ePMRfJc.gif
    icon: https://img.alicdn.com/imgextra/i4/O1CN012VRqMx1zBevGk6jyA_!!6000000006676-2-tps-200-200.png

- greeting:
    text_size: md
    text:  永远相信，美好的事情即将发生！

# - resources:
#     cpu: true
#     memory: true
#     # disk: /

# - search:
#     # provider: duckduckgo
#     # target: _blank
#     provider: google # google, duckduckgo, bing, baidu or custom
#     focus: true # Optional, will set focus to the search bar on page load
#     target: _blank # One of _self, _blank, _parent or _top

# - weatherapi:
#     label: 杭州 # optional
#     latitude: 30.321118
#     longitude: 120.132738
#     units: metric # or imperial
#     provider: weatherapi
#     cache: 5 # Time in minutes to cache API responses, to stay within limits

# - datetime:
#     text_size: 2xl
#     format:
#       timeStyle: short
#       hour12: true
  
