version: "3.0"

services:
  myip:
    image: jason5ng32/myip:latest
    container_name: myip
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - 28966:18966
    networks:
      - dokploy-network
    labels:
      # - traefik.enable=true
      # - traefik.http.routers.myip.rule=Host(`myip.godd.site`)
      # - traefik.http.routers.myip.entrypoints=web
      # - traefik.http.services.myip.loadbalancer.server.port=18966
      - homepage.group=Public
      - homepage.name=myip
      - homepage.icon=https://myip.godd.site:6443/logos/ios-logo-512.png
      - homepage.href=https://myip.godd.site:6443
      - homepage.description=查询IP，出口IP，IP信息
      - com.centurylinklabs.watchtower.enable=true

networks:
  dokploy-network:
    external: true
